### ISSUE TITLE
Error: results.reduce is not a function when running example code.

### ISSUE THREAD

**Issue by ReviewEdge** [foo-software/lighthouse-check-status-action#19]
I'm getting this error while whenever I try to "Verify Lighthouse Check Results" and set minimum scores for the test to pass:
![image](https://user-images.githubusercontent.com/27935830/148252165-5fa58880-2940-4a50-a396-c7d634d8d571.png)

My code is almost straight from the example in the docs so I'm not sure what could be going wrong:

```
  lighthouse:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'
    - run: mkdir ${{ github.workspace }}/tmp
    - run: mkdir ${{ github.workspace }}/tmp/artifacts
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        urls: 'https://staging.digitellinc.io, https://staging.digitellinc.io/staging/live/3/page/39, https://staging.digitellinc.io/staging/live/3/page/44'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: ${{ github.workspace }}/tmp/artifacts
    - name: Verify Lighthouse Check results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "85"
        minBestPracticesScore: "83"
        minPerformanceScore: "30"
        minProgressiveWebAppScore: "48"
        minSeoScore: "80"
```
